# === Stackworld default config ===
# Base world and ordered stacks upward and downward.
baseWorld: "world"

stack:
  up:
    - name: "skyworld"
      createIfMissing: true
      environment: NORMAL      # NORMAL | NETHER | THE_END
      type: CUSTOM             # NORMAL | SUPERFLAT | CUSTOM
      generator: "the_void"    # datapack/plugin generator key
      seed: 12345
      ambiance:
        skylightAtBottom: true
        eternalNight: false
      copy:
        height: 32
        areaXZ: 201            # square side length around player (odd)
        blocksPerTick: 4000
        mode: OVERWRITE        # OVERWRITE | AIR_ONLY
        cleanup: true
        blacklist: [BEDROCK, WATER, LAVA, GLASS]
        tileEntities: true

    - name: "space"
      createIfMissing: true
      environment: THE_END
      type: CUSTOM
      generator: "the_void"
      seed: 9876
      ambiance:
        eternalNight: true
      copy:
        height: 32

  down:
    - name: "caveWorld"
      createIfMissing: true
      environment: NORMAL
      type: CUSTOM
      generator: "cave_full"
      bottomBoundaryY: -120
    - name: "hollowEarth"
      createIfMissing: true
      environment: NORMAL
      type: CUSTOM
      generator: "hollow_mega"
    - name: "lavaWorld"
      createIfMissing: true
      environment: NORMAL
      type: CUSTOM
      generator: "lava_void"

teleport:
  midSwitch:
    enabled: true
    hysteresis: 6        # ±3 around the band center
  cooldownMs: 60000

safety:
  safePlatform:
    enabled: true
    block: GLASS
    size: 3
  holdDuringCopyMs: 10000
