name: Stackworld
main: de.ella.stackworld.Stackworld
version: 1.2.0
api-version: '1.21'
authors: [ 'Ella' ]
website: 'https://example.invalid/stackworld'
commands:
  stackworld:
    description: Stackworld admin commands
    usage: |
      /<command> reload - reloads config
      /<command> info   - shows current edge/band info
      /<command> where  - shows your position relative to bands
    aliases: [ sw ]
permissions:
  stackworld.reload:
    description: Allow /stackworld reload
    default: op
  stackworld.info:
    description: Allow /stackworld info/where
    default: true
